version: '3.8'
services:
  web:
    image: pccms:latest
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - SHOW_DOCS=true
  db:
    image: postgres:16-bullseye
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: ["-c", "max_connections=500","-c", "shared_buffers=1024MB"]

volumes:
  postgres_data:
