version: '3.8'
services:
  web:
    image: pccms:latest
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      - SHOWDOCS=${SHOWDOCS}
      - DATABASE_URL=${DATABASE_URL}
  db:
    image: postgres:16-bullseye
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: ["-c", "max_connections=2500","-c", "shared_buffers=1024MB"]

volumes:
  postgres_data:

